### ISSUE TITLE
Conflict dragging when adding script

### ISSUE THREAD

**Issue by martijnzoutman** [DHTMLGoodies/jquery-on-off-switch#1]
There's a conflict when the in page script for a custom switch is added. On mobile devices the page is not scrollable (ios and android). Also other controls in the same page that are draggable are not working. So obviously something goes wrong with dragging globally. You can test it on the http://www.jqueryscript.net/form/Custom-On-Off-Toggle-Switch-Plugin-For-jQuery-on-off-switch-js.html page yourself, it displays the same problem as described on mobile.

**Comment by DHTMLGoodies** [comment]
This issue has been resolved today.

**Comment by martijnzoutman** [comment]
The scrolling issue has been resolved.
1. However when the plugin is used together with input fields, these fields are not editable on mobile.
2. Also there's a conflict with other controls that have dragging / slider functionality. Once used they seem to remain having status focused, and they slide along when adjusting another. Somehow your plugin's dragging functionality is not limited to your control.

**Comment by DHTMLGoodies** [comment]
I've added another fix which hopefully solves this problem.

**Comment by martijnzoutman** [comment]
The js files do not seem to be updated

**Comment by DHTMLGoodies** [comment]
How about now? :)

**Comment by martijnzoutman** [comment]
Superb support! TY
